"""Public types and validation helpers for the open capsule format."""

from bugcapsule.capsule.archive import (
    ArchiveLimits,
    CapsuleArchive,
    CapsuleArchiveError,
    CapsuleIntegrityError,
    CapsuleSecurityError,
    ImportedCapsule,
    create_manifest,
)
from bugcapsule.capsule.identifiers import canonical_json, sha256_hex, stable_identifier
from bugcapsule.capsule.redaction import RedactionResult, RedactionRule, Redactor
from bugcapsule.capsule.schema import (
    CapsuleFile,
    CapsuleManifest,
    EnvironmentInfo,
    EvidenceItem,
    EvidenceKind,
    EvidenceReferenceError,
    GitInfo,
    PatchCandidate,
    RedactionFinding,
    RedactionReport,
    RootCauseCandidate,
    ServiceInfo,
    TestResult,
    TraceInfo,
    VerificationRun,
    validate_evidence_references,
)

__all__ = [
    "ArchiveLimits",
    "CapsuleArchive",
    "CapsuleArchiveError",
    "CapsuleFile",
    "CapsuleIntegrityError",
    "CapsuleManifest",
    "CapsuleSecurityError",
    "EnvironmentInfo",
    "EvidenceItem",
    "EvidenceKind",
    "EvidenceReferenceError",
    "GitInfo",
    "ImportedCapsule",
    "PatchCandidate",
    "RedactionFinding",
    "RedactionReport",
    "RedactionResult",
    "RedactionRule",
    "Redactor",
    "RootCauseCandidate",
    "ServiceInfo",
    "TestResult",
    "TraceInfo",
    "VerificationRun",
    "canonical_json",
    "create_manifest",
    "sha256_hex",
    "stable_identifier",
    "validate_evidence_references",
]
